apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
    - name: subdirectory
      type: string
      default: ""
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.url) $(workspaces.output.path)/$(params.subdirectory)
        cd $(workspaces.output.path)/$(params.subdirectory)
        git checkout $(params.revision)
